platform :ios, '12.4'
use_frameworks!

target 'nativebridge-ios_Example' do
  pod 'nativebridge-ios', :path => '../'
end

target 'nativebridge-ios_Tests' do
  pod 'nativebridge-ios', :path => '../'
end
